### ISSUE TITLE
Review and Update Batch-Session-Attendance Pages

### ISSUE THREAD

**Issue by swapneelrane** [gitmedha/sis-frontend#13]
**Describe the task**
Most functionality for these pages have already been built. You'll need to review code and clean up UI.

- [x] Remove batch 6 and associated records
- [x] Add button for "Enroll Students" in the Students section
- [x] #44
- [x] Round up to Integers in Attendance Progress Bar (see screenshow below)
- [x] Add pagination in Sessions table on Batch page (e.g. https://sis-new.medha.org.in/batch/1). Currently shows all records.
- [x] Show Student count in Batch list view: https://sis-new.medha.org.in/batches
- [x] Change page title of Batch list view to"My Batches": https://sis-new.medha.org.in/batches
- [x] Add Medha favicon
- [x] Fix query for picklist field config on Students table on Batch page (see https://github.com/gitmedha/medha-react-ui/issues/13#issuecomment-903511403)
- [x] In Detail view, render the Institution Name as a clickable link to the respective Institution page (see https://github.com/gitmedha/medha-react-ui/issues/13#issuecomment-900140115)
- [x] Ensure sessions table can be sorted on the batch page (see: https://github.com/gitmedha/medha-react-ui/issues/13#issuecomment-900153352 )

**Expected behavior**
1. CRUD functionality for Batches & Sessions
2. CRUD for Session & Attendance happens together (e.g. if you delete a session, all associated attendance records should be deleted)
3. If new students are added to batch after it has started and sessions have been created, system should allow user to retroactively update attendance for the new students for the previously created sessions.
![image](https://user-images.githubusercontent.com/21273738/126959534-b66fb9ef-87dc-48a4-aaa7-cad3cd786ff4.png)

**References**
See data model below
![image](https://user-images.githubusercontent.com/21273738/126959792-3fef4657-a317-4fae-b307-50524b45e9f2.png)
